### ISSUE TITLE
Auto Vote Error

### ISSUE THREAD

**Issue by LastRomanCeIMP** [titaniummachine1/Beta_Luas#1]
I installed Auto-Vote Lua. When I activate Lua, it automatically starts writing to the chat when entering any match or server. Normally he doesn't write unless the voting starts. However, when I activate it from the menu, it starts writing automatically when I enter any server, but it does not start writing automatically after entering the game unless I activate it from the menu. For some reason, such a situation does not occur when you activate it after entering
![image](https://github.com/user-attachments/assets/202eba36-9831-480f-97d4-a66cefae0c66)
 the match.

**Comment by titaniummachine1** [comment]
fixed the issue it was single liner

```lua
    if not (msg:GetID() == VoteStart) then return end --fix the code working every time someone sends any mesage

```

this checks if mesage sent is the vote cast if not it will not do anything if yes it will alet plaeyrs about your vote target beeign chacker
